-- Snowflake DQ HOL: Quick Setup (all Module 0 SQL in one file)
-- Run as ACCOUNTADMIN before the workshop

-- Database + Schemas
CREATE DATABASE IF NOT EXISTS CORP_DWH COMMENT = 'Corporate Data Warehouse - Snowflake DQ Monitoring HOL';
CREATE SCHEMA IF NOT EXISTS CORP_DWH.RAW COMMENT = 'Bronze: raw data as-is from source systems';
CREATE SCHEMA IF NOT EXISTS CORP_DWH.SILVER COMMENT = 'Silver: cleansed, unified, scored (Dynamic Tables)';
CREATE SCHEMA IF NOT EXISTS CORP_DWH.GOLD COMMENT = 'Gold: business-ready dimensions and facts (dbt models)';
CREATE SCHEMA IF NOT EXISTS CORP_DWH.DQ COMMENT = 'Data Quality: DMFs, rules catalog, procedures, alerts';

-- Roles
CREATE ROLE IF NOT EXISTS CORP_DQ_ADMIN;
GRANT USAGE ON DATABASE CORP_DWH TO ROLE CORP_DQ_ADMIN;
GRANT USAGE ON ALL SCHEMAS IN DATABASE CORP_DWH TO ROLE CORP_DQ_ADMIN;
GRANT ALL PRIVILEGES ON SCHEMA CORP_DWH.RAW TO ROLE CORP_DQ_ADMIN;
GRANT ALL PRIVILEGES ON SCHEMA CORP_DWH.SILVER TO ROLE CORP_DQ_ADMIN;
GRANT ALL PRIVILEGES ON SCHEMA CORP_DWH.GOLD TO ROLE CORP_DQ_ADMIN;
GRANT ALL PRIVILEGES ON SCHEMA CORP_DWH.DQ TO ROLE CORP_DQ_ADMIN;
GRANT CREATE DATA METRIC FUNCTION ON SCHEMA CORP_DWH.DQ TO ROLE CORP_DQ_ADMIN;
GRANT CREATE DYNAMIC TABLE ON SCHEMA CORP_DWH.SILVER TO ROLE CORP_DQ_ADMIN;
GRANT CREATE DYNAMIC TABLE ON SCHEMA CORP_DWH.GOLD TO ROLE CORP_DQ_ADMIN;
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE CORP_DQ_ADMIN;
GRANT APPLICATION ROLE SNOWFLAKE.DATA_QUALITY_MONITORING_VIEWER TO ROLE CORP_DQ_ADMIN;
GRANT EXECUTE DATA METRIC FUNCTION ON ACCOUNT TO ROLE CORP_DQ_ADMIN;
GRANT DATABASE ROLE SNOWFLAKE.DATA_METRIC_USER TO ROLE CORP_DQ_ADMIN;
GRANT ROLE CORP_DQ_ADMIN TO ROLE ACCOUNTADMIN;

CREATE ROLE IF NOT EXISTS CORP_DQ_STEWARD;
GRANT USAGE ON DATABASE CORP_DWH TO ROLE CORP_DQ_STEWARD;
GRANT USAGE ON ALL SCHEMAS IN DATABASE CORP_DWH TO ROLE CORP_DQ_STEWARD;
GRANT ALL PRIVILEGES ON SCHEMA CORP_DWH.DQ TO ROLE CORP_DQ_STEWARD;
GRANT CREATE DATA METRIC FUNCTION ON SCHEMA CORP_DWH.DQ TO ROLE CORP_DQ_STEWARD;
GRANT SELECT ON ALL TABLES IN SCHEMA CORP_DWH.RAW TO ROLE CORP_DQ_STEWARD;
GRANT SELECT ON ALL TABLES IN SCHEMA CORP_DWH.SILVER TO ROLE CORP_DQ_STEWARD;
GRANT SELECT ON ALL TABLES IN SCHEMA CORP_DWH.GOLD TO ROLE CORP_DQ_STEWARD;
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE CORP_DQ_STEWARD;
GRANT EXECUTE DATA METRIC FUNCTION ON ACCOUNT TO ROLE CORP_DQ_STEWARD;
GRANT APPLICATION ROLE SNOWFLAKE.DATA_QUALITY_MONITORING_VIEWER TO ROLE CORP_DQ_STEWARD;
GRANT ROLE CORP_DQ_STEWARD TO ROLE CORP_DQ_ADMIN;

-- Cross-region inference (required for Cortex AI in non-US regions)
ALTER ACCOUNT SET CORTEX_ENABLED_CROSS_REGION = 'ANY_REGION';

-- Notification integration (replace email before running!)
-- CREATE OR REPLACE NOTIFICATION INTEGRATION CORP_DQ_ALERTS
--     TYPE = EMAIL ENABLED = TRUE
--     ALLOWED_RECIPIENTS = ('<<YOUR_EMAIL>>');
-- GRANT USAGE ON INTEGRATION CORP_DQ_ALERTS TO ROLE CORP_DQ_ADMIN;
