-- Snowflake DQ HOL: Teardown (all cleanup in one file)
-- Run as ACCOUNTADMIN after the workshop

USE ROLE ACCOUNTADMIN;

-- Suspend active objects
ALTER ALERT IF EXISTS CORP_DWH.DQ.ALERT_DQ_FAILURES SUSPEND;
ALTER TASK IF EXISTS CORP_DWH.DQ.TASK_HOURLY_DQ_SWEEP SUSPEND;

-- Drop everything
DROP DATABASE IF EXISTS CORP_DWH;
DROP ROLE IF EXISTS CORP_DQ_ADMIN;
DROP ROLE IF EXISTS CORP_DQ_STEWARD;
DROP INTEGRATION IF EXISTS CORP_DQ_ALERTS;
